# This workflow will create a release based on the major, minor and patch version of NPM package
# The workflow will be manually triggered in git hub actions.
# Install semantic-release on your local environment

name: Node.js package 
on: 
  
  workflow_dispatch:
      
jobs:
  Release-publish:
    name: Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm install && npm run build
      - name: Create a release
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}  
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
   
     