name: release workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: Publish Package? 
        default: publish
        required: false
  #push:
   # branches:
    #  - main
jobs:
  release-deployment:
    runs-on: ubuntu-latest
    steps:
        ### This stage will check out the code from parallel-mono repo into the runner using Version 2 of the action.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 ###Required to retrieve git history. This will fetch all history for all tags and branches when fetch-depth=0 
      - name: Create a release
        ##if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail