name: terraform workflows

on: [push]

jobs:
    defaults:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: hashicorp/setup-terraform@v1
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PHRASE" --output $HOME/.aws/credentials creds.gpg
        env:
          PHRASE: ${{ secrets.PHRASE }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true