name: shell commands

on: [push]

env:
  WF_ENV: ${{ secrets.WF_ENV }}

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.txt my_secret.txt.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Print our file
        run: cat $HOME/secret.txt
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls -a 
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Poowershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  


          
